Repository ngoworldcommunity/NGOWorld-Backend, pull requests merged in 2023-10, with the labels that each got.

#31 feat: added event schema
  schema/events/EventSchema.js
Labels: hacktoberfest-accepted, 🟢 status: ready to merge, area/logic, 💡 feature

#38 feat: added fields to club schema
  schema/club/ClubSchema.js
Labels: hacktoberfest-accepted, status: ready ☑, 💡 feature

#45 fix: user Route and Google Oauth
  routes/display/Display.js
  routes/user/Auth.js
  routes/user/User.js
Labels: hacktoberfest-accepted, status: ready ☑, 🐞 bug

#39 feat: implemented create event route
  config/api.yaml
  index.js
  routes/events/Event.js
  utils/SetTime.js
  utils/Status.js
Labels: hacktoberfest-accepted, status: ready ☑, 💡 feature
